"""add version to monitors

Revision ID: f69d8f800147
Revises: 71e1620d1ab0
Create Date: 2026-09-15 14:14:42.252634

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f69d8f800147"
down_revision: str | Sequence[str] | None = "71e1620d1ab0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monitors", sa.Column("version", sa.Integer(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitors", "version")
    # ### end Alembic commands ###
