apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsewatch-config
data:
  POSTGRES_USER: pulsewatch
  POSTGRES_DB: pulsewatch
  REDIS_URL: redis://redis:6379/0
  SMTP_HOST: mailpit
  SMTP_PORT: "1025"
  FRONTEND_URL: http://localhost:5173
  ENVIRONMENT: production